spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:ijuju_test;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: INFO