##  http://localhost:8090/h2-console
server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:./ijuju_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    com.example.com.programs.ijuju: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE