spring:
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true